Project:
  Name : C2000_A2_SDXA000_AX1
  RT_ID : 5156
  File : "C2000-A2-SDXA000-AX1-使用说明书[2020-03-27].pdf"
  DevType : 2
  Category : 传感器
  ProtocolName : 康耐德16DI
Sample :
  - Cmd : 2
    Offset : 0x64
    Len : 16
    Data : 
      - Name : DI1
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI2
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI3
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI4
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI5
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI6
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI7
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI8
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI9
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI10
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI11
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI12
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI13
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI14
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI15
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : DI16
        Options : 
          - Key : 0
            Value : 断开
          - Key : 1
            Value : 闭合
      - Name : 液位1
        Value : '( $v[2] == 0 ) ? 85 : 79'
        CValue : '( pData[1] == 0 ) ? 85 : 79'
      - Name : 液位2
        Value : '( $v[4] == 0 ) ? 85 : 79'
        CValue : '( pData[3] == 0 ) ? 85 : 79'