Project:
  Name : DTS541
  RT_ID : 5156
  File : "DTS541 交流多回路智能电能表(2_4_8回路,导轨式)用户手册.doc"
  DevType : 2
  Category : 智能电表
  ProtocolName : DTS541智能电表
BlockTemplate: 
  ChannelInfo:
    BlockLength : 80
    BlockType : 'f'
    BlockContent :
      - Name : "第%s回路-回路号"
      - Name : "第%s回路-A相电流"
        Unit : A
      - Name : "第%s回路-B相电流"
        Unit : A
      - Name : "第%s回路-C相电流"
        Unit : A
      - Name : "第%s回路-零序电流"
        Unit : A
      - Name : "第%s回路-A相有功功率"
        Unit : kW
      - Name : "第%s回路-B相有功功率"
        Unit : kW
      - Name : "第%s回路-C相有功功率"
        Unit : kW
      - Name : "第%s回路-总有功功率"
        Unit : kW
      - Name : "第%s回路-A相无功功率"
        Unit : kVar
      - Name : "第%s回路-B相无功功率"
        Unit : kVar
      - Name : "第%s回路-C相无功功率"
        Unit : kVar
      - Name : "第%s回路-总无功功率"
        Unit : kVar
      - Name : "第%s回路-总功率因数"
      - Name : "第%s回路-总有功电能"
        Unit : kWh
      - Name : "第%s回路-总无功电能"
        Unit : kVarh
      - Name : "第%s回路-正向有功电能"
        Unit : kWh
      - Name : "第%s回路-反向有功电能"
        Unit : kWh
      - Name : "第%s回路-正向无功电能"
        Unit : kVarh
      - Name : "第%s回路-反向无功电能"
        Unit : kVarh
Sample :
  - Cmd : 3
    Offset : 4000
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 1
  - Cmd : 3
    Offset : 4040
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 2
  - Cmd : 3
    Offset : 4080
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 3
  - Cmd : 3
    Offset : 4120
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 4
  - Cmd : 3
    Offset : 4160
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 5
  - Cmd : 3
    Offset : 4200
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 6
  - Cmd : 3
    Offset : 4240
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 7
  - Cmd : 3
    Offset : 4280
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 8
  - Cmd : 3
    Offset : 4320
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 9
  - Cmd : 3
    Offset : 4360
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 10
  - Cmd : 3
    Offset : 4400
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 11
  - Cmd : 3
    Offset : 4440
    Len : 40
    Data : 
      - Block : ChannelInfo
        index : 12
  - Cmd : 3
    Offset : 4480
    Len : 8
    Type : 'f'
    Data : 
      - Name : A相电压
      - Name : B相电压
      - Name : C相电压
      - Name : 频率
  - Cmd : 3
    Offset : 4500
    Len : 13
    Data : 
      - Name : PT
      - Name : 第1回路CT额定电流
      - Name : 第2回路CT额定电流
      - Name : 第3回路CT额定电流
      - Name : 第4回路CT额定电流
      - Name : 第5回路CT额定电流
      - Name : 第6回路CT额定电流
      - Name : 第7回路CT额定电流
      - Name : 第8回路CT额定电流
      - Name : 第9回路CT额定电流
      - Name : 第10回路CT额定电流
      - Name : 第11回路CT额定电流
      - Name : 第12回路CT额定电流