Project:
  Name : FengJi2
  RT_ID : 5156
  File : "点位2025124.xlsx 194.94.77.57 RS485-3 地址11 副CPU"
  DevType : 2
  BaudRate : 4800
  Category : 专用空调
  ProtocolName : 风机节能2
Sample : 
  - Cmd : 3
    Offset : 252
    Len : 28
    RType : 'f'
    Data : 
      - Name : 1#风机频率给定
        Unit : Hz
      - Name : 2#风机频率给定
        Unit : Hz
      - Name : 3#风机频率给定
        Unit : Hz
      - Name : 4#风机频率给定
        Unit : Hz
      - Name : 5#风机频率给定
        Unit : Hz
      - Name : 6#风机频率给定
        Unit : Hz
      - Name : 7#风机频率给定
        Unit : Hz
      - Name : 8#风机频率给定
        Unit : Hz
      - Name : 9#风机频率给定
        Unit : Hz
      - Name : 10#风机频率给定
        Unit : Hz
      - Name : 11#风机频率给定
        Unit : Hz
      - Name : 12#风机频率给定
        Unit : Hz
      - Name : 1#水泵频率给定
        Unit : Hz
      - Name : 2#水泵频率给定
        Unit : Hz
  - Cmd : 3
    Offset : 55
    Len : 3
    Data : 
      - Name : 1#风机手自动
        Value : ($v[1]>>8)&0x1
        CValue : (pData[0]>>8)&0x1
      - Name : 1#风机运行
        Value : ($v[1]>>9)&0x1
        CValue : (pData[0]>>9)&0x1
      - Name : 1#风机故障
        Value : ($v[1]>>10)&0x1
        CValue : (pData[0]>>10)&0x1
        AlertNormalValue : 0
        TelePSignalId : 12017
      - Name : 2#风机手自动
        Value : ($v[1]>>11)&0x1
        CValue : (pData[0]>>11)&0x1
      - Name : 2#风机运行
        Value : ($v[1]>>12)&0x1
        CValue : (pData[0]>>12)&0x1
      - Name : 2#风机故障
        Value : ($v[1]>>13)&0x1
        CValue : (pData[0]>>13)&0x1
        AlertNormalValue : 0
        TelePSignalId : 12017
      - Name : 1#阀开到位
        Value : ($v[1]>>14)&0x1
        CValue : (pData[0]>>14)&0x1
      - Name : 1#阀关到位
        Value : ($v[1]>>15)&0x1
        CValue : (pData[0]>>15)&0x1
      - Name : 2#阀开到位
        Value : ($v[1]>>0)&0x1
        CValue : (pData[0]>>0)&0x1
      - Name : 2#阀关到位
        Value : ($v[1]>>1)&0x1
        CValue : (pData[0]>>1)&0x1
      - Name : 3#阀开到位
        Value : ($v[1]>>2)&0x1
        CValue : (pData[0]>>2)&0x1
      - Name : 3#阀关到位
        Value : ($v[1]>>3)&0x1
        CValue : (pData[0]>>3)&0x1
      - Name : 4#阀开到位
        Value : ($v[1]>>4)&0x1
        CValue : (pData[0]>>4)&0x1
      - Name : 4#阀关到位
        Value : ($v[1]>>5)&0x1
        CValue : (pData[0]>>5)&0x1
      - Name : 5#阀开到位
        Value : ($v[1]>>6)&0x1
        CValue : (pData[0]>>6)&0x1
      - Name : 5#阀关到位
        Value : ($v[1]>>7)&0x1
        CValue : (pData[0]>>7)&0x1
      - Name : 6#阀开到位
        Value : ($v[2]>>8)&0x1
        CValue : (pData[1]>>8)&0x1
      - Name : 6#阀关到位
        Value : ($v[2]>>9)&0x1
        CValue : (pData[1]>>9)&0x1
      - Name : 7#阀开到位
        Value : ($v[2]>>10)&0x1
        CValue : (pData[1]>>10)&0x1
      - Name : 7#阀关到位
        Value : ($v[2]>>11)&0x1
        CValue : (pData[1]>>11)&0x1
      - Name : 8#阀开到位
        Value : ($v[2]>>12)&0x1
        CValue : (pData[1]>>12)&0x1      
      - Name : 8#阀关到位
        Value : ($v[2]>>13)&0x1
        CValue : (pData[1]>>13)&0x1
      - Name : 9#阀开到位
        Value : ($v[2]>>14)&0x1
        CValue : (pData[1]>>14)&0x1
      - Name : 9#阀关到位
        Value : ($v[2]>>15)&0x1
        CValue : (pData[1]>>15)&0x1
      - Name : 10#阀开到位
        Value : ($v[2]>>0)&0x1
        CValue : (pData[1]>>0)&0x1
      - Name : 11#阀关到位
        Value : ($v[2]>>1)&0x1
        CValue : (pData[1]>>1)&0x1
      - Name : 1#阀门远程
        Value : ($v[2]>>2)&0x1
        CValue : (pData[1]>>2)&0x1
      - Name : 2#阀门远程
        Value : ($v[2]>>3)&0x1
        CValue : (pData[1]>>3)&0x1
      - Name : 3#阀门远程
        Value : ($v[2]>>4)&0x1
        CValue : (pData[1]>>4)&0x1
      - Name : 4#阀门远程
        Value : ($v[2]>>5)&0x1
        CValue : (pData[1]>>5)&0x1
      - Name : 5#阀门远程
        Value : ($v[2]>>6)&0x1
        CValue : (pData[1]>>6)&0x1
      - Name : 6#阀门远程
        Value : ($v[2]>>7)&0x1
        CValue : (pData[1]>>7)&0x1
      - Name : 7#阀门远程
        Value : ($v[3]>>8)&0x1
        CValue : (pData[2]>>8)&0x1
      - Name : 8#阀门远程
        Value : ($v[3]>>9)&0x1
        CValue : (pData[2]>>9)&0x1
      - Name : 9#阀门远程
        Value : ($v[3]>>10)&0x1
        CValue : (pData[2]>>10)&0x1
      - Name : 10#阀门远程
        Value : ($v[3]>>11)&0x1
        CValue : (pData[2]>>11)&0x1