Project:
  Name : HuaYiZFSLTianJinLu
  RT_ID : 5156
  File : "天津路联通换热485通讯地址0520(华奕）.xls"
  DevType : 2
  ProtocolName : 天津路联通换热
  Category : 新风设备
Sample : 
  - Cmd : 3
    Offset : 0
    Len : 36
    Data : 
      - Name : 机组手动运行/自动启动
        Offset : 1
        Options :
          - Key : 0
            Value : 手动
          - Key : 1
            Value : 自动
      - Name : 远程/本地
        Offset : 3
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : 机组状态
        Offset : 4
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵1报警
        Offset : 5
        AlertNormalValue : 0
      - Name : 水泵2报警
        Offset : 6
        AlertNormalValue : 0
      - Name : 水泵3报警
        Offset : 7
        AlertNormalValue : 0
      - Name : 水泵4报警
        Offset : 8
        AlertNormalValue : 0
      - Name : 补水泵1报警
        Offset : 10
        AlertNormalValue : 0
      - Name : 补水泵2报警
        Offset : 11
        AlertNormalValue : 0
      - Name : 水箱1#低水位
        Offset : 12
        AlertNormalValue : 0
      - Name : 水箱2#低水位
        Offset : 13
        AlertNormalValue : 0
      - Name : 水箱3#低水位
        Offset : 14
        AlertNormalValue : 0
      - Name : 水箱4#低水位
        Offset : 15
        AlertNormalValue : 0
      - Name : 消防联动
        Offset : 16
        AlertNormalValue : 0
      - Name : 水泵1运行状态
        Offset : 18
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵2运行状态
        Offset : 19
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵3运行状态
        Offset : 20
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 水泵4运行状态
        Offset : 21
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 潜水泵1运行状态
        Offset : 23
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 潜水泵2运行状态
        Offset : 24
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 排水阀1运行状态
        Offset : 25
        Options :
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 打开
      - Name : 排水阀2运行状态
        Offset : 26
        Options :
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 打开
      - Name : 排水阀3运行状态
        Offset : 27
        Options :
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 打开
      - Name : 排水阀4运行状态
        Offset : 28
        Options :
          - Key : 0
            Value : 关闭
          - Key : 1
            Value : 打开
      - Name : 风机1运行状态
        Offset : 29
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 风机2运行状态
        Offset : 30
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 风机3运行状态
        Offset : 31
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 风机4运行状态
        Offset : 32
        Options :
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 风机1报警
        Offset : 33
        AlertNormalValue : 0
      - Name : 风机2报警
        Offset : 34
        AlertNormalValue : 0
      - Name : 风机3报警
        Offset : 35
        AlertNormalValue : 0
      - Name : 风机4报警
        Offset : 36
        AlertNormalValue : 0
  - Cmd : 3
    Offset : 46
    Len : 44
    RType : "f"
    Data : 
      - Name : 盘管1压力
        Offset : 1
      - Name : 盘管2压力
        Offset : 2
      - Name : 盘管3压力
        Offset : 3
      - Name : 盘管4压力
        Offset : 4
      - Name : 盘管1温度
        Offset : 5
      - Name : 盘管2温度
        Offset : 6
      - Name : 盘管3温度
        Offset : 7
      - Name : 盘管4温度
        Offset : 8
      - Name : 风机1频率反馈
        Offset : 9
      - Name : 风机2频率反馈
        Offset : 10
      - Name : 风机3频率反馈
        Offset : 11
      - Name : 风机4频率反馈
        Offset : 12
      - Name : 蓄水箱液位
        Offset : 13
      - Name : 室外温度
        Offset : 16
      - Name : 室外湿度
        Offset : 17
      - Name : 湿球温度
        Offset : 18
    
      