Project:
  Name : InnoTemperature
  RT_ID : 5156
  File : "RS485通讯规约.pdf"
  DevType : 2
  ProtocolName : 福州英诺温控器
  Category : 开关电源
Sample : 
  - Cmd : 3
    Offset : 0
    Len : 3
    Data :
      - Name : A相温度数据
        Value : '($v[1]>>12) ? -9999 : ($v[1]&0x0FFF)/10'
        CValue : '(pData[0]>>12) ? -9999 : (pData[0]&0x0FFF)/10'
        Unit : ℃
      - Name : B相温度数据
        Value : '($v[2]>>12) ? -9999 : ($v[2]&0x0FFF)/10'
        CValue : '(pData[1]>>12) ? -9999 : (pData[1]&0x0FFF)/10'
        Unit : ℃
      - Name : C相温度数据
        Value : '($v[3]>>12) ? -9999 : ($v[3]&0x0FFF)/10'
        CValue : '(pData[2]>>12) ? -9999 : (pData[2]&0x0FFF)/10'
        Unit : ℃
  - Cmd : 4
    Offset : 0
    Len : 1
    Data :
      - Name : ⻛机控制
        Value : ($v[1] & 0x1)
        CValue : (pData[0] & 0x1)
        AlertNormalValue : 0
      - Name : 超温跳闸
        Value : (($v[1]>>1) & 0x1)
        CValue : ((pData[0]>>1) & 0x1)
        AlertNormalValue : 0
      - Name : 超温报警
        Value : (($v[1]>>2) & 0x1)
        CValue : ((pData[0]>>2) & 0x1)
        AlertNormalValue : 0
      - Name : 故障报警
        Value : (($v[1]>>3) & 0x1)
        CValue : ((pData[0]>>3) & 0x1)
        AlertNormalValue : 0
        