Project:
  Name : JSFsensor1
  RT_ID : 5156
  File : "联通未来城二期BA点表(1)(1).xlsx IP:172.18.21.16"
  DevType : 2
  Category : 专用空调
  ProtocolName : 流量传感器
Sample : 
  - Cmd : 0
    Offset : [10506,10416,10509]
    Ip : 172.18.21.12
    Data : [ 冷冻水总管供水支路1流量测量,冷冻水总管回水支路1流量测量,冷却水环管回水总管路流量测量（泵与冷塔之间）]
  - Cmd : 2
    Offset : [3000612,3000632,3000633]
    Ip : 172.18.21.11
    Data : [ 冷冻水总管回水支路1流量测量1,冷冻水总管供水支路1流量测量1,冷却水环管回水总管路流量测量（泵与冷塔之间） ]
UnicomAI :   
  冷冻水总管供水支路1流量测量 : alcwsfr,A路冷冻供水流量
  冷冻水总管回水支路1流量测量 : alcwrfr,A路冷冻回水流量
  冷冻水总管回水支路1流量测量1 : blcwsfr,B路冷冻供水流量
  冷冻水总管供水支路1流量测量1 : blcwrfr,B路冷冻回水流量
  冷却水环管回水总管路流量测量（泵与冷塔之间） : alcwsfr,A路冷却回水流量
  冷却水环管回水总管路流量测量（泵与冷塔之间） : alcwrfr,B路冷却回水流量
