Project:
  Name : MS10
  RT_ID : 5156
  File : "MS10F(G)通讯地址表.xls"
  DevType : 2
  ProtocolName : MS10FG智能电表定点数
  Category : 智能电表
Sample : 
  - Cmd : 3
    Offset : 0x46
    Len : 23
    Data : 
      - Name : "A相电压"
        Ratio : 10
        Unit : "V"
      - Name : "B相电压"
        Ratio : 10
        Unit : "V"
      - Name : "C相电压"
        Ratio : 10
        Unit : "V"
      - Name : AB相线电压
        Ratio : 10
        Unit : "V"
      - Name : BC相线电压
        Ratio : 10
        Unit : "V"
      - Name : CA相线电压
        Ratio : 10
        Unit : "V"
      - Name : A相电流
        Ratio : 1000
        Unit : "A"
      - Name : B相电流
        Ratio : 1000
        Unit : "A"
      - Name : C相电流
        Ratio : 1000
        Unit : "A"
      - Name : A相有功功率
        Ratio : 1000
        Unit : "kW"
      - Name : B相有功功率
        Ratio : 1000
        Unit : "kW"
      - Name : C相有功功率
        Ratio : 1000
        Unit : "kW"
      - Name : 总有功功率
        Ratio : 1000
        Unit : "kW"
      - Name : A相无功功率
        Ratio : 1000
        Unit : "kVar"
      - Name : B相无功功率
        Ratio : 1000
        Unit : kVar
      - Name : C相无功功率
        Ratio : 1000
        Unit : kVar
      - Name : 总无功功率
        Ratio : 1000
        Unit : kVar
      - Name : A相视在功率
        Ratio : 1000
        Unit : kVA
      - Name : B相视在功率
        Ratio : 1000  
        Unit : kVA
      - Name : C相视在功率
        Ratio : 1000
        Unit : kVA
      - Name : 总视在功率
        Ratio : 1000
        Unit : kVA
      - Name : 总功率因数
        Ratio : 1000
      - Name : 电压频率 
        Ratio : 100
        Unit : Hz
  - Cmd : 3
    Offset : 0x5D
    Len : 8
    Data : 
      - Name : 正向有功电能
        Value : (($v[1]<<16)|$v[2])/1000
        CValue : ((pData[0]<<16|pData[1]))/1000
        Unit : "kWh"
      - Name : 反向有功电能 
        Value : (($v[3]<<16)|$v[4])/1000
        CValue : ((pData[2]<<16|pData[3]))/1000
        Unit : "kWh"
      - Name : 感性无功电能
        Value : (($v[5]<<16)|$v[6])/1000
        CValue : ((pData[4]<<16|pData[5]))/1000
        Unit : "kVarh"
      - Name : 容性无功电能
        Value : (($v[7]<<16)|$v[8])/1000
        CValue : ((pData[6]<<16|pData[7]))/1000
        Unit : "kVarh"


     