Project:
  Name : PMF910L
  RT_ID : 5156
  File : "PMF910(B码)-Modbus规约点表V3.1 20201105 - 副本(1).pdf"
  DevType : 2
  ProtocolName : PMF910L微机保护测控装置
  Category : 传感器
Sample :
  - Cmd : 3
    Offset : 0
    Len : 2
    Data : 
      - Name : "远方/就地"
        Value : ($v[1]&0x1)
        CValue : (pData[0]&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "断路器跳位"
        Value : (($v[1]>>1)&0x1)
        CValue : ((pData[0]>>1)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "断路器合位"
        Value : (($v[1]>>2)&0x1)
        CValue : ((pData[0]>>2)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "检修压板"
        Value : (($v[1]>>3)&0x1)
        CValue : ((pData[0]>>3)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "弹簧未储能"
        Value : (($v[1]>>4)&0x1)
        CValue : ((pData[0]>>4)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "接地刀"
        Value : (($v[1]>>5)&0x1)
        CValue : ((pData[0]>>5)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "试验位/下隔离"
        Value : (($v[1]>>6)&0x1)
        CValue : ((pData[0]>>6)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "工作位/上隔离"
        Value : (($v[1]>>7)&0x1)
        CValue : ((pData[0]>>7)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "开入8"
        Value : (($v[1]>>8)&0x1)
        CValue : ((pData[0]>>8)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "开入7"
        Value : (($v[1]>>9)&0x1)
        CValue : ((pData[0]>>9)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "开入6"
        Value : (($v[1]>>10)&0x1)
        CValue : ((pData[0]>>10)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "开入5"
        Value : (($v[1]>>11)&0x1)
        CValue : ((pData[0]>>11)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "非电量4开入"
        Value : (($v[1]>>12)&0x1)
        CValue : ((pData[0]>>12)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "非电量3开入"
        Value : (($v[1]>>13)&0x1)
        CValue : ((pData[0]>>13)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "充电硬压板"
        Value : (($v[1]>>14)&0x1)
        CValue : ((pData[0]>>14)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "闭锁重合闸"
        Value : (($v[1]>>15)&0x1)
        CValue : ((pData[0]>>15)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "A/D出错"
        Value : (($v[2]>>6)&0x1)
        CValue : ((pData[1]>>6)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "出口配置出错"
        Value : (($v[2]>>7)&0x1)
        CValue : ((pData[1]>>7)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "参数出错"
        Value : (($v[2]>>8)&0x1)
        CValue : ((pData[1]>>8)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "定值出错"
        Value : (($v[2]>>9)&0x1)
        CValue : ((pData[1]>>9)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "定值区号出错"
        Value : (($v[2]>>10)&0x1)
        CValue : ((pData[1]>>10)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "充电状态"
        Value : (($v[2]>>11)&0x1)
        CValue : ((pData[1]>>11)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "定值区EEPROM出错号出错"
        Value : (($v[2]>>12)&0x1)
        CValue : ((pData[1]>>12)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "事故总信号"
        Value : (($v[2]>>13)&0x1)
        CValue : ((pData[1]>>13)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "预告总信号"
        Value : (($v[2]>>14)&0x1)
        CValue : ((pData[1]>>14)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "手跳开入"
        Value : (($v[2]>>15)&0x1)
        CValue : ((pData[1]>>15)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
  - Cmd : 3
    Offset : 3
    Len : 3
    Data : 
      - Name : "跳位异常压板"
        Value : (($v[1]>>1)&0x1)
        CValue : ((pData[0]>>1)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "弹簧未储能压板"
        Value : (($v[1]>>2)&0x1)
        CValue : ((pData[0]>>2)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "TV 断线压板"
        Value : (($v[1]>>3)&0x1)
        CValue : ((pData[0]>>3)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "控制回路断线压板"
        Value : (($v[1]>>4)&0x1)
        CValue : ((pData[0]>>4)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "充电保护压板"
        Value : (($v[1]>>5)&0x1)
        CValue : ((pData[0]>>5)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "低频减载压板"
        Value : (($v[1]>>6)&0x1)
        CValue : ((pData[0]>>6)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "重合闸压板"
        Value : (($v[1]>>7)&0x1)
        CValue : ((pData[0]>>7)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "低电压压板"
        Value : (($v[1]>>8)&0x1)
        CValue : ((pData[0]>>8)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "过负荷压板"
        Value : (($v[1]>>9)&0x1)
        CValue : ((pData[0]>>9)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "零序过流压板"
        Value : (($v[1]>>10)&0x1)
        CValue : ((pData[0]>>10)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "过流反时限压板"
        Value : (($v[1]>>11)&0x1)
        CValue : ((pData[0]>>11)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "过流加速压板"
        Value : (($v[1]>>12)&0x1)
        CValue : ((pData[0]>>12)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "电流Ⅲ段压板"
        Value : (($v[1]>>13)&0x1)
        CValue : ((pData[0]>>13)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "电流Ⅱ段压板"
        Value : (($v[1]>>14)&0x1)
        CValue : ((pData[0]>>14)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入
      - Name : "电流Ⅰ段压板"
        Value : (($v[1]>>15)&0x1)
        CValue : ((pData[0]>>15)&0x1)
        Options : 
          - Key : 0
            Value : 退出
          - Key : 1
            Value : 投入

      - Name : "跳位异常压板"
        Value : (($v[3]>>1)&0x1)
        CValue : ((pData[2]>>1)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "弹簧未储能"
        Value : (($v[3]>>2)&0x1)
        CValue : ((pData[2]>>2)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "TV 断线检测"
        Value : (($v[3]>>3)&0x1)
        CValue : ((pData[2]>>3)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "控制回路断线检测"
        Value : (($v[3]>>4)&0x1)
        CValue : ((pData[2]>>4)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "充电保护"
        Value : (($v[3]>>5)&0x1)
        CValue : ((pData[2]>>5)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "低频减载"
        Value : (($v[3]>>6)&0x1)
        CValue : ((pData[2]>>6)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "重合闸"
        Value : (($v[3]>>7)&0x1)
        CValue : ((pData[2]>>7)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "低电压"
        Value : (($v[3]>>8)&0x1)
        CValue : ((pData[2]>>8)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "过负荷"
        Value : (($v[3]>>9)&0x1)
        CValue : ((pData[2]>>9)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "零序过流"
        Value : (($v[3]>>10)&0x1)
        CValue : ((pData[2]>>10)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "过流反时限"
        Value : (($v[3]>>11)&0x1)
        CValue : ((pData[2]>>11)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "过流加速"
        Value : (($v[3]>>12)&0x1)
        CValue : ((pData[2]>>12)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "电流Ⅲ段跳闸"
        Value : (($v[3]>>13)&0x1)
        CValue : ((pData[2]>>13)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "电流Ⅱ段跳闸"
        Value : (($v[3]>>14)&0x1)
        CValue : ((pData[2]>>14)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
      - Name : "电流Ⅰ段跳闸"
        Value : (($v[3]>>15)&0x1)
        CValue : ((pData[2]>>15)&0x1)
        Options : 
          - Key : 0
            Value : 返回
          - Key : 1
            Value : 动作
  - Cmd : 3
    Offset : 7
    Len : 20
    Data : 
      - Name : "A相保护电流"
        Ratio : 100
        Unit : "A"
      - Name : "B相保护电流"
        Ratio : 100
        Unit : "A"
      - Name : "C相保护电流"
        Ratio : 100
        Unit : "A"
      - Name : "零序电流"
        Ratio : 100
        Unit : "A"
      - Name : "A相测量电流"
        Ratio : 100
        Unit : "A"
      - Name : "B相测量电流"
        Ratio : 100
        Unit : "A"
      - Name : "C相测量电流"
        Ratio : 100
        Unit : "A"
      - Name : "A相电压"
        Ratio : 100
        Unit : "V"
      - Name : "B相电压"
        Ratio : 100
        Unit : "V"
      - Name : "C相电压"
        Ratio : 100
        Unit : "V"
      - Name : "AB线电压"
        Ratio : 100
        Unit : "V"
      - Name : "BC线电压"
        Ratio : 100
        Unit : "V"
      - Name : "CA线电压"
        Ratio : 100
        Unit : "V"
      - Name : "零序电压"
        Ratio : 100
        Unit : "V"
      - Name : "负序电压"
        Ratio : 100
        Unit : "V"
      - Name : "P"
        Ratio : 1000
        Unit : "kW"
      - Name : "Q"
        Ratio : 1000
        Unit : "kVar"
      - Name : "COS"
        Ratio : 100
      - Name : "f"
        Ratio : 100
        Unit : Hz