Project:
  Name : SPM322020MODBUS 
  RT_ID : 5156
  File : "SPM32（2020）MODBUS串行通信协议V1.8"
Sample : 
  - Cmd : 3
    Offset : 40
    Len : 2
    Data : 
      - Name : "CT变比"
      - Name : "PT变比"
  - Cmd : 3
    Offset : 0
    Len : 2
    Data : 
      - Name : "A相电压"
        Ratio : 100
        Unit : V
      - Name : "B相电压"
        Ratio : 100
        Unit : V
      - Name : "C相电压"
        Ratio : 100
        Unit : V
      - Name : "AB线电压"
        Ratio : 100
        Unit : V
      - Name : "BC线电压"
        Ratio : 100
        Unit : V
      - Name : "CA线电压"
        Ratio : 100
        Unit : V
      - Name : "A相电流"
        Ratio : 1000
        Unit : A
      - Name : "B相电流"
        Ratio : 1000
        Unit : A
      - Name : "C相电流"
        Ratio : 1000
        Unit : A
      - Name : "零序电流"
        Ratio : 1000
        Unit : A
        
      - Name : "总有功功率"
      - Name : "总无功功率"
      - Name : "总功率因数"
      - Name : "A 相有功功率"
      - Name : "B 相有功功率"
      - Name : "C 相有功功率"
      - Name : "A 相无功功率"
      - Name : "B 相无功功率"
      - Name : "C 相无功功率"
      - Name : "A 相功率因数"
      - Name : "B 相功率因数"
      - Name : "C 相功率因数"
      - Name : "频率"
      - Name : "有功电能总和"
      - Name : "无功电能总和"
      - Name : "输入有功电能"
      - Name : "输出有功电能"
      - Name : "输入无功电能"
      - Name : "输出无功电能"
      - Name : "开关量状态"
      - Name : "继电器状态"
      - Name : "报警状态"

      - Name : "平均相电压"
      - Name : "平均线电压"
      - Name : "平均相电流"
      - Name : "三相电流不平衡率"
      - Name : "A 相视在功率"
      - Name : "B 相视在功率"
      - Name : "C 相视在功率"
      - Name : "总视在功率"
      - Name : "视在电能总和"
      - Name : "三相电压不平衡率"
      - Name : "电压零序分量"
      - Name : "电压正序分量"
      - Name : "电压负序分量"
      - Name : "A 相电压角度"
      - Name : "B 相电压角度"
      - Name : "C 相电压角度"
      - Name : "A 相电流角度"
      - Name : "B 相电流角度"
      - Name : "C 相电流角度"
      - Name : "仪表运行时间LRC"
      - Name : "负载上电时间"
      - Name : "LOH"
      - Name : "负载运行时间LRH"
      - Name : "A 相负载阻抗"
      - Name : "B 相负载阻抗"
      - Name : "C 相负载阻抗"
      - Name : "总负载阻抗"
