Project:
  Name : SUTemperature3
  RT_ID : 5156
  File : "群里截图"
  DevType : 2
  Category : 传感器
  ProtocolName : SUTemperature3
Sample : 
  - Cmd : 4
    Offset : 0x400
    Len : 1
    Data :
      - Name : 温度值
        Unit : ℃