Project:
  Name : UnicomPowerMeter
  RT_ID : 5156
  File : "联通-多功能电力仪表.docx"
  DevType : 2
  ProtocolName : "多功能电力仪表"
  Category : 智能电表
Sample : 
  - Cmd : 3
    Offset : 0xA
    Len : 60
    RType : 'f'
    Data :
      - Name : A相电压
        Unit : V
      - Name : B相电压
        Unit : V
      - Name : C相电压
        Unit : V
      - Name : AB相线电压
        Unit : V
      - Name : BC相线电压
        Unit : V
      - Name : CA相线电压
        Unit : V
      - Name : A相电流
        Unit : A
      - Name : B相电流
        Unit : A
      - Name : C相电流
        Unit : A
      - Name : A相有功功率
        Ratio : 1000
        Unit : kW
      - Name : B相有功功率
        Ratio : 1000
        Unit : kW
      - Name : C相有功功率
        Ratio : 1000
        Unit : kW
      - Name : 总有功功率
        Ratio : 1000
        Unit : kW
      - Name : A相无功功率
        Ratio : 1000
        Unit : kVar
      - Name : B相无功功率
        Ratio : 1000
        Unit : kVar
      - Name : C相无功功率
        Ratio : 1000
        Unit : kVar
      - Name : 总无功功率
        Ratio : 1000
        Unit : kVar
      - Name : 总视在功率
        Ratio : 1000
        Unit : kVA
      - Name : 总功率因数
      - Name : 电压频率
      - Name : 正向有功电能
        Unit : kWh
      - Name : 反向有功电能
        Unit : kWh
      - Name : 感性无功电能
        Unit : kVarh
      - Name : 容性无功电能
        Unit : kVarh
      - Name : A相功率因数
      - Name : B相功率因数
      - Name : C相功率因数
      - Name : A相视在功率
        Ratio : 1000
        Unit : kVA
      - Name : B相视在功率
        Ratio : 1000
        Unit : kVA
      - Name : C相视在功率
        Ratio : 1000
        Unit : kVA