Project:
  Name : WHB890
  RT_ID : 5156
  File : "WHB-890系列装置 MODBUS规约点表 V1.00.pdf"
  DevType : 2
  ProtocolName : "WHB-890综合保护"
  Category : 传感器
Sample : 
  - Cmd : 3
    Offset : 0xA
    Len : 60
    RType : 'f'
    Data :