Project:
  Name : XJBAXuLengGuan
  RT_ID : 5156
  File : "新疆二枢纽BA数据MODBUS_TCP协议25.7.8.xls - 蓄冷罐"
  DevType : 4
  ProtocolName : 新疆二枢纽BA蓄冷罐
  Category : 专用空调
BlockTemplate: 
  ValveAction:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s动作状态-本地/远程"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "%s动作状态-开到位"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未开到位
          - Key : 1
            Value : 开到位
      - Name : "%s动作状态-关到位"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未关到位
          - Key : 1
            Value : 关到位
      - Name : "%s动作状态-开故障"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 开阀故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s动作状态-关故障"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 关阀故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s动作状态-故障汇总"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s动作状态-开过程中"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        Options : 
          - Key : 0
            Value : 无动作
          - Key : 1
            Value : 开阀过程中
      - Name : "%s动作状态-关过程中"
        CValue : ((pData[1]>>7) & 0x1)
        Value : (($v[2]>>7) & 0x1)
        Options : 
          - Key : 0
            Value : 无动作
          - Key : 1
            Value : 关阀过程中
      - Name : "%s动作状态-中间状态"
        CValue : ((pData[1]>>8) & 0x1)
        Value : (($v[2]>>8) & 0x1)
        Options : 
          - Key : 0
            Value : 未处于中间状态
          - Key : 1
            Value : 中间状态
  ValveControl:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s控制状态-手动/自动"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 自动
          - Key : 1
            Value : 手动
  SensorStatus:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s-断线报警使能"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-预警使能"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-报警使能"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-高报警"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-高预警"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-低预警"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-低报警"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-断线报警"
        CValue : ((pData[1]>>9) & 0x1)
        Value : (($v[2]>>9) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
Sample : 
  - Cmd : 1
    Offset : 146
    Len : 3
    Data : 
      - Name : "总管电动阀MV2-1本地/远程"
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "总管电动阀MV2-1失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : 总管电动阀MV2-1软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
  - Cmd : 3
    Offset : 830
    Len : 16
    RType : 'f'
    Data : 
      - Name : 蓄冷罐电动阀MV2-1开度反馈
        Unit : '%'
      - Name : 蓄冷罐进水温度1
        Unit : "℃"
      - Name : 蓄冷罐出水温度1
        Unit : "℃"
      - Name : 蓄冷罐流量
        Unit : "m³/h"
      - Name : 蓄冷罐充冷管道压力1
        Unit : "bar"
      - Name : 蓄冷罐进水温度2
        Unit : "℃"
      - Name : 蓄冷罐出水温度2
        Unit : "℃"
      - Name : 蓄冷罐充冷管道压力2
        Unit : bar
  - Cmd : 3
    Offset : 890
    Len : 38
    Data : 
      - Block : ValveAction
        index : 蓄冷罐电动阀SV9-2动作状态
      - Block : ValveControl
        index : 蓄冷罐电动阀SV9-2控制状态
      - Block : ValveAction
        index : 蓄冷罐电动阀SV11-2动作状态
      - Block : ValveControl
        index : 蓄冷罐电动阀SV11-2控制状态
      - Block : ValveAction
        index : 蓄冷罐电动阀SV18-2动作状态
      - Block : ValveControl
        index : 蓄冷罐电动阀SV18-2控制状态
      - Block : SensorStatus
        index : 蓄冷罐进水温度1状态
      - Block : SensorStatus
        index : 蓄冷罐出水温度1状态
      - Block : SensorStatus
        index : 蓄冷罐流量状态
      - Block : SensorStatus
        index : 蓄冷罐充冷管道压力1状态
      - Block : ValveAction
        index : 蓄冷罐电动阀SV9-1动作状态
      - Block : ValveControl
        index : 蓄冷罐电动阀SV9-1控制状态
      - Block : ValveAction
        index : 蓄冷罐电动阀SV11-1动作状态
      - Block : ValveControl
        index : 蓄冷罐电动阀SV11-1控制状态
      - Block : ValveAction
        index : 蓄冷罐电动阀SV18-1动作状态
      - Block : ValveControl
        index : 蓄冷罐电动阀SV18-1控制状态
      - Block : SensorStatus
        index : 蓄冷罐进水温度2状态
      - Block : SensorStatus
        index : 蓄冷罐出水温度2状态
      - Block : SensorStatus
        index : 蓄冷罐充冷管道压力2状态
     
