Project:
  Name : XJBASanDanYuan
  RT_ID : 5156
  File : "新疆二枢纽BA数据MODBUS_TCP协议25.7.8.xls - 三单元"
  DevType : 4
  ProtocolName : 新疆二枢纽BA三单元
  Category : 专用空调
BlockTemplate: 
  ValveAction:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s动作状态-本地/远程"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "%s动作状态-开到位"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未开到位
          - Key : 1
            Value : 开到位
      - Name : "%s动作状态-关到位"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未关到位
          - Key : 1
            Value : 关到位
      - Name : "%s动作状态-开故障"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 开阀故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s动作状态-关故障"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 关阀故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s动作状态-故障汇总"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s动作状态-开过程中"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        Options : 
          - Key : 0
            Value : 无动作
          - Key : 1
            Value : 开阀过程中
      - Name : "%s动作状态-关过程中"
        CValue : ((pData[1]>>7) & 0x1)
        Value : (($v[2]>>7) & 0x1)
        Options : 
          - Key : 0
            Value : 无动作
          - Key : 1
            Value : 关阀过程中
      - Name : "%s动作状态-中间状态"
        CValue : ((pData[1]>>8) & 0x1)
        Value : (($v[2]>>8) & 0x1)
        Options : 
          - Key : 0
            Value : 未处于中间状态
          - Key : 1
            Value : 中间状态
  ValveControl:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s控制状态-手动/自动"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 自动
          - Key : 1
            Value : 手动
  SensorStatus:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s-断线报警使能"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-预警使能"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-报警使能"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-高报警"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-高预警"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-低预警"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-低报警"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-断线报警"
        CValue : ((pData[1]>>9) & 0x1)
        Value : (($v[2]>>9) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
Sample : 
  - Cmd : 1
    Offset : 64
    Len : 32
    Data : 
      - Name : "三单元电动阀MV3本地/远程"
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "三单元电动阀MV3失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : 三单元电动阀MV3软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 三单元电动阀MV4本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : 三单元电动阀MV4失调
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : 三单元电动阀MV4软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 冷冻泵3本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : 冷冻泵3运行
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 冷冻泵3故障
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : 冷冻泵3合闸信号1
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 冷冻泵3合闸信号2
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 冷冻泵3软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 三单元冷却泵本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : 三单元冷却泵运行
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 三单元冷却泵故障
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : 三单元冷却泵合闸信号1
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 三单元冷却泵合闸信号2
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 三单元冷却泵软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 三单元冷机运行
        Offset : 20
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 三单元冷机故障
        Offset : 21
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : 三单元冷机合闸信号
        Offset : 22
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 三单元冷机软手自动
        Offset : 23
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 三单元冷却塔本地/远程
        Offset : 24
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : 三单元冷却塔运行
        Offset : 25
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 三单元冷却塔故障
        Offset : 26
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : 三单元冷却塔合闸信号
        Offset : 27
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 三单元冷却塔软手自动
        Offset : 28
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : DDF-1F-02阀门柜主电合闸
        Offset : 29
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : DDF-1F-02阀门柜备电合闸
        Offset : 30
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : PLC104主电合闸
        Offset : 31
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : PLC104备电合闸
        Offset : 32
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
  - Cmd : 3
    Offset : 304
    Len : 60
    RType : 'f'
    Data : 
      - Name : 三单元电动阀MV3开度反馈
        Unit : '%'
      - Name : 三单元电动阀MV4开度反馈
        Unit : '%'
      - Name : 冷冻泵2频率反馈
        Unit : "Hz"
      - Name : 三单元冷却泵频率反馈
        Unit : "Hz"
      - Name : 三单元冷机冷冻进水温度
        Unit : "℃"
      - Name : 三单元冷机冷冻出水温度
        Unit : "℃"
      - Name : 三单元冷机冷却进水温度
        Unit : "℃"
      - Name : 三单元冷机冷却出水温度
        Unit : "℃"
      - Name : 三单元板换冷冻进水温度
        Unit : "℃"
      - Name : 三单元板换冷冻出水温度
        Unit : "℃"
      - Name : 三单元板换冷却进水温度
        Unit : "℃"
      - Name : 三单元板换冷却出水温度
        Unit : "℃"
      - Name : 三单元冷冻侧流量
        Unit : "m³/h"
      - Name : 三单元冷却侧流量
        Unit : "m³/h"
      - Name : 三单元冷机冷媒
        Unit : "ppm"
      - Name : 冷冻泵3进水压力
        Unit : "bar"
      - Name : "冷冻泵3出水压力"
        Unit : "bar"
      - Name : 三单元冷却泵进水压力
        Unit : "bar"
      - Name : 三单元冷却泵出水压力
        Unit : bar
      - Name : 三单元冷却塔液位
        Unit : mm
      - Name : 三单元冷却塔夏季出水温度1
        Unit : "℃"
      - Name : 三单元冷却塔夏季出水温度2
        Unit : "℃"
      - Name : 三单元板换冷冻进水压力
        Unit : bar
      - Name : 三单元板换冷冻出水压力
        Unit : bar
      - Name : 三单元板换冷却进水压力
        Unit : bar
      - Name : 三单元板换冷却出水压力
        Unit : bar
      - Name : 三单元冷机冷冻进水压力
        Unit : bar
      - Name : 三单元冷机冷冻出水压力
        Unit : bar
      - Name : 三单元冷机冷却进水压力
        Unit : bar
      - Name : 三单元冷机冷却出水压力
        Unit : bar
  - Cmd : 3
    Offset : 364
    Len : 92
    Data : 
      - Block : ValveAction
        index : 三单元电动阀SV1
      - Block : ValveControl
        index : 三单元电动阀SV1
      - Block : ValveAction
        index : 三单元电动阀SV2
      - Block : ValveControl
        index : 三单元电动阀SV2
      - Block : ValveAction
        index : 三单元电动阀SV3
      - Block : ValveControl
        index : 三单元电动阀SV3
      - Block : ValveAction
        index : 三单元电动阀SV4
      - Block : ValveControl
        index : 三单元电动阀SV4
      - Block : ValveAction
        index : 三单元电动阀SV5
      - Block : ValveControl
        index : 三单元电动阀SV5
      - Block : ValveAction
        index : 三单元电动阀SV6
      - Block : ValveControl
        index : 三单元电动阀SV6
      - Block : ValveAction
        index : 三单元电动阀SV12
      - Block : ValveControl
        index : 三单元电动阀SV12
      - Block : ValveAction
        index : 三单元电动阀SV13
      - Block : ValveControl
        index : 三单元电动阀SV13
      - Block : ValveAction
        index : 三单元电动阀SV16
      - Block : ValveControl
        index : 三单元电动阀SV16
      - Block : ValveAction
        index : 三单元电动阀SV17
      - Block : ValveControl
        index : 三单元电动阀SV17
      - Block : SensorStatus
        index : 三单元冷机冷冻进水温度状态
      - Block : SensorStatus
        index : 三单元冷机冷冻出水温度状态
      - Block : SensorStatus
        index : 三单元冷机冷却进水温度状态
      - Block : SensorStatus
        index : 三单元冷机冷却出水温度状态
      - Block : SensorStatus
        index : 三单元板换冷冻进水温度状态
      - Block : SensorStatus
        index : 三单元板换冷冻出水温度状态
      - Block : SensorStatus
        index : 三单元板换冷却进水温度状态
      - Block : SensorStatus
        index : 三单元板换冷却出水温度状态
      - Block : SensorStatus
        index : 三单元冷冻侧流量状态
      - Block : SensorStatus
        index : 三单元冷却侧流量状态
      - Block : SensorStatus
        index : 三单元冷机冷媒状态
      - Block : SensorStatus
        index : 冷冻泵3进水压力状态
      - Block : SensorStatus
        index : 冷冻泵3出水压力状态
      - Block : SensorStatus
        index : 三单元冷却泵进水压力状态
      - Block : SensorStatus
        index : 三单元冷却泵出水压力状态
      - Block : SensorStatus
        index : 三单元冷却塔液位状态
      - Block : SensorStatus
        index : 三单元冷却塔夏季出水温度1状态
      - Block : SensorStatus
        index : 三单元冷却塔夏季出水温度2状态
      - Block : SensorStatus
        index : 三单元板换冷冻进水压力状态
      - Block : SensorStatus
        index : 三单元板换冷冻出水压力状态
      - Block : SensorStatus
        index : 三单元板换冷却进水压力状态
      - Block : SensorStatus
        index : 三单元板换冷却出水压力状态
      - Block : SensorStatus
        index : 三单元冷机冷冻进水压力状态
      - Block : SensorStatus
        index : 三单元冷机冷冻出水压力状态
      - Block : SensorStatus
        index : 三单元冷机冷却进水压力状态
      - Block : SensorStatus
        index : 三单元冷机冷却出水压力状态
