Project:
  Name : XJBAXuLengGuanTongXun
  RT_ID : 5156
  File : "新疆二枢纽BA数据MODBUS_TCP协议25.7.8.xls - 蓄冷罐通讯"
  DevType : 4
  ProtocolName : 新疆二枢纽BA蓄冷罐通讯
  Category : 专用空调
Sample:
  - Cmd : 3
    Offset : 2434
    Len : 38
    RType : 'f'
    Data : 
      - Name : 蓄冷罐压力
        Unit : 'bar'
      - Name : 蓄冷罐温度1
        Unit : "℃"
      - Name : 蓄冷罐温度2
        Unit : "℃"
      - Name : 蓄冷罐温度3
        Unit : "℃"
      - Name : 蓄冷罐温度4
        Unit : "℃"
      - Name : 蓄冷罐温度5
        Unit : "℃"
      - Name : 蓄冷罐温度6
        Unit : "℃"
      - Name : 蓄冷罐温度7
        Unit : "℃"
      - Name : 蓄冷罐温度8
        Unit : "℃"
      - Name : 蓄冷罐温度9
        Unit : "℃"
      - Name : 蓄冷罐温度10
        Unit : "℃"
      - Name : 蓄冷罐温度11
        Unit : "℃"
      - Name : 蓄冷罐温度12
        Unit : "℃"
      - Name : 蓄冷罐温度13
        Unit : "℃"
      - Name : 蓄冷罐温度14
        Unit : "℃"
      - Name : 蓄冷罐温度15
        Unit : "℃"
      - Name : 蓄冷罐温度16
        Unit : "℃"
      - Name : 蓄冷罐温度17
        Unit : "℃"
      - Name : 蓄冷罐温度18
        Unit : "℃"
      