Project:
  Name : XJBASiDanYuan
  RT_ID : 5156
  File : "新疆二枢纽BA数据MODBUS_TCP协议25.7.8.xls - 四单元"
  DevType : 4
  ProtocolName : 新疆二枢纽BA四单元
  Category : 专用空调
BlockTemplate: 
  ValveAction:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s动作状态-本地/远程"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "%s动作状态-开到位"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未开到位
          - Key : 1
            Value : 开到位
      - Name : "%s动作状态-关到位"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未关到位
          - Key : 1
            Value : 关到位
      - Name : "%s动作状态-开故障"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 开阀故障
      - Name : "%s动作状态-关故障"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 关阀故障
      - Name : "%s动作状态-故障汇总"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
      - Name : "%s动作状态-开过程中"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        Options : 
          - Key : 0
            Value : 无动作
          - Key : 1
            Value : 开阀过程中
      - Name : "%s动作状态-关过程中"
        CValue : ((pData[1]>>7) & 0x1)
        Value : (($v[2]>>7) & 0x1)
        Options : 
          - Key : 0
            Value : 无动作
          - Key : 1
            Value : 关阀过程中
      - Name : "%s动作状态-中间状态"
        CValue : ((pData[1]>>8) & 0x1)
        Value : (($v[2]>>8) & 0x1)
        Options : 
          - Key : 0
            Value : 未处于中间状态
          - Key : 1
            Value : 中间状态
  ValveControl:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s控制状态-手动/自动"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 自动
          - Key : 1
            Value : 手动
  SensorStatus:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s-断线报警使能"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-预警使能"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-报警使能"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-高报警"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        AlertNormalValue : 0
      - Name : "%s-高预警"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        AlertNormalValue : 0
      - Name : "%s-低预警"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        AlertNormalValue : 0
      - Name : "%s-低报警"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        AlertNormalValue : 0
      - Name : "%s-断线报警"
        CValue : ((pData[1]>>9) & 0x1)
        Value : (($v[2]>>9) & 0x1)
        AlertNormalValue : 0
Sample : 
  - Cmd : 1
    Offset : 96
    Len : 15
    Data : 
      - Name : "四单元电动阀MV5本地/远程"
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "四单元电动阀MV5失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
      - Name : 四单元电动阀MV5软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 四单元冷却泵本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : 四单元冷却泵运行
        Options : 
          - Key : 0
            Value : 停止
          - Key : 1
            Value : 运行
      - Name : 四单元冷却泵故障
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
      - Name : 四单元冷却泵合闸信号1
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 四单元冷却泵合闸信号2
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 四单元冷却泵软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : DDF-1F-03阀门柜主电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : DDF-1F-03阀门柜备电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : PLC105主电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : PLC105备电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : DDF-1F-07阀门柜主电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : DDF-1F-07阀门柜备电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
  - Cmd : 3
    Offset : 456
    Len : 32
    RType : 'f'
    Data : 
      - Name : 四单元电动阀MV5开度反馈
        Unit : '%'
      - Name : 四单元冷却泵频率反馈
        Unit : "Hz"
      - Name : 四单元板换冷冻进水温度
        Unit : "℃"
      - Name : 四单元板换冷冻出水温度
        Unit : "℃"
      - Name : 四单元板换冷却进水温度
        Unit : "℃"
      - Name : 四单元板换冷却出水温度
        Unit : "℃"
      - Name : 四单元冷冻侧流量
        Unit : "m³/h"
      - Name : 四单元冷却侧流量
        Unit : "m³/h"
      - Name : 四单元冷却泵进水压力
        Unit : "bar"
      - Name : 四单元冷却泵出水压力
        Unit : bar
      - Name : 四单元冷却塔冬季出水温度1
        Unit : "℃"
      - Name : 四单元冷却塔冬季出水温度2
        Unit : "℃"
      - Name : 四单元板换冷冻进水压力
        Unit : bar
      - Name : 四单元板换冷冻出水压力
        Unit : bar
      - Name : 四单元板换冷却进水压力
        Unit : bar
      - Name : 四单元板换冷却出水压力
        Unit : bar
  - Cmd : 3
    Offset : 488
    Len : 44
    Data : 
      - Block : ValveAction
        index : 四单元电动阀SV7
      - Block : ValveControl
        index : 四单元电动阀SV7
      - Block : ValveAction
        index : 四单元电动阀SV8
      - Block : ValveControl
        index : 四单元电动阀SV8
      - Block : ValveAction
        index : 四单元电动阀SV14
      - Block : ValveControl
        index : 四单元电动阀SV14
      - Block : ValveAction
        index : 四单元电动阀SV15
      - Block : ValveControl
        index : 四单元电动阀SV15
        index : 四单元板换冷冻进水温度状态
      - Block : SensorStatus
        index : 四单元板换冷冻出水温度状态
      - Block : SensorStatus
        index : 四单元板换冷却进水温度状态
      - Block : SensorStatus
        index : 四单元板换冷却出水温度状态
      - Block : SensorStatus
        index : 四单元冷冻侧流量状态
      - Block : SensorStatus
        index : 四单元冷却侧流量状态
      - Block : SensorStatus
        index : 四单元冷却泵进水压力状态
      - Block : SensorStatus
        index : 四单元冷却泵出水压力状态
      - Block : SensorStatus
        index : 四单元冷却塔冬季出水温度1状态
      - Block : SensorStatus
        index : 四单元冷却塔冬季出水温度2状态
      - Block : SensorStatus
        index : 四单元板换冷冻进水压力状态
      - Block : SensorStatus
        index : 四单元板换冷冻出水压力状态
      - Block : SensorStatus
        index : 四单元板换冷却进水压力状态
      - Block : SensorStatus
        index : 四单元板换冷却出水压力状态
