Project:
  Name : XJBAHuanGuan
  RT_ID : 5156
  File : "新疆二枢纽BA数据MODBUS_TCP协议25.7.8.xls - 环管"
  DevType : 4
  ProtocolName : 新疆二枢纽BA环管
  Category : 专用空调
BlockTemplate: 
  ValveAction:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s动作状态-本地/远程"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "%s动作状态-开到位"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未开到位
          - Key : 1
            Value : 开到位
      - Name : "%s动作状态-关到位"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未关到位
          - Key : 1
            Value : 关到位
      - Name : "%s动作状态-开故障"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 开阀故障
      - Name : "%s动作状态-关故障"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 关阀故障
      - Name : "%s动作状态-故障汇总"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 故障
      - Name : "%s动作状态-开过程中"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        Options : 
          - Key : 0
            Value : 无动作
          - Key : 1
            Value : 开阀过程中
      - Name : "%s动作状态-关过程中"
        CValue : ((pData[1]>>7) & 0x1)
        Value : (($v[2]>>7) & 0x1)
        Options : 
          - Key : 0
            Value : 无动作
          - Key : 1
            Value : 关阀过程中
      - Name : "%s动作状态-中间状态"
        CValue : ((pData[1]>>8) & 0x1)
        Value : (($v[2]>>8) & 0x1)
        Options : 
          - Key : 0
            Value : 未处于中间状态
          - Key : 1
            Value : 中间状态
  ValveControl:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s控制状态-手动/自动"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 自动
          - Key : 1
            Value : 手动
  SensorStatus:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s-断线报警使能"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-预警使能"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-报警使能"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-高报警"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        AlertNormalValue : 0
      - Name : "%s-高预警"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        AlertNormalValue : 0
      - Name : "%s-低预警"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        AlertNormalValue : 0
      - Name : "%s-低报警"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        AlertNormalValue : 0
      - Name : "%s-断线报警"
        CValue : ((pData[1]>>9) & 0x1)
        Value : (($v[2]>>9) & 0x1)
        AlertNormalValue : 0
Sample : 
  - Cmd : 1
    Offset : 405
    Len : 15
    Data : 
      - Name : PLC100主电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : PLC100备电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : PLC101主电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : PLC101备电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : "冷冻环管旁通电动阀CV1-2本地/远程"
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "冷冻环管旁通电动阀CV1-2失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
      - Name : 冷冻环管旁通电动阀CV1-2软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 冷却环管旁通电动阀MV6-1本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "冷却环管旁通电动阀MV6-1失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
      - Name : 冷却环管旁通电动阀MV6-1软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 冷却环管旁通电动阀MV7-1本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "冷却环管旁通电动阀MV7-1失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
      - Name : 冷却环管旁通电动阀MV7-1软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : DDF-1F-05阀门柜主电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : DDF-1F-05阀门柜备电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : 冷冻环管旁通电动阀CV1-1本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "冷冻环管旁通电动阀CV1-1失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
      - Name : 冷冻环管旁通电动阀CV1-1软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 冷却环管旁通电动阀MV6-2本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "冷却环管旁通电动阀MV6-2失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
      - Name : 冷却环管旁通电动阀MV6-2软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : 冷却环管旁通电动阀MV7-2本地/远程
        Options : 
          - Key : 0
            Value : 本地
          - Key : 1
            Value : 远程
      - Name : "冷却环管旁通电动阀MV7-2失调"
        Options : 
          - Key : 0
            Value : 正常
          - Key : 1
            Value : 失调
      - Name : 冷却环管旁通电动阀MV7-2软手自动
        Options : 
          - Key : 0
            Value : 软自动
          - Key : 1
            Value : 软手动
      - Name : DDF-1F-06阀门柜主电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
      - Name : DDF-1F-06阀门柜备电合闸
        Options : 
          - Key : 0
            Value : 分闸
          - Key : 1
            Value : 合闸
  - Cmd : 3
    Offset : 832
    Len : 70
    RType : 'f'
    Data : 
      - Name : 冷冻环管旁通电动阀CV1-2开度反馈
        Unit : '%'
      - Name : 冷却环管旁通电动阀MV6-1开度反馈
        Unit : '%'
      - Name : 冷却环管旁通电动阀MV7-1开度反馈
        Unit : '%'
      - Name : 末端冷冻环管供水温度2
        Unit : "℃"
      - Name : 末端冷冻环管回水温度2
        Unit : "℃"
      - Name : 末端冷冻环管供水压力2
        Unit : bar
      - Name : 末端冷冻环管回水压力2
        Unit : bar
      - Name : 冷冻回水环管温度2
        Unit : "℃"
      - Name : 冷冻回水环管压力2
        Unit : bar
      - Name : 夏季冷却供水环管温度1
        Unit : "℃"
      - Name : 夏季冷却回水环管温度1
        Unit : "℃"
      - Name : 夏季冷却供水环管压力1
        Unit : bar
      - Name : 夏季冷却回水环管压力1
        Unit : bar
      - Name : 冬季冷却供水环管温度1
        Unit : "℃"
      - Name : 冬季冷却回水环管温度1
        Unit : "℃"
      - Name : 冬季冷却供水环管压力1
        Unit : bar
      - Name : 冬季冷却回水环管压力1
        Unit : bar
      - Name : 电导率
        Unit : "μs/cm"
      - Name : 冷冻环管旁通电动阀CV1-1开度反馈
        Unit : "%"
      - Name : 冷却环管旁通电动阀MV6-2开度反馈
        Unit : "%"
      - Name : 冷却环管旁通电动阀MV7-2开度反馈
        Unit : "%"
      - Name : 末端冷冻环管供水温度1
        Unit : "℃"
      - Name : 末端冷冻环管回水温度1
        Unit : "℃"
      - Name : 末端冷冻环管供水压力1
        Unit : bar
      - Name : 末端冷冻环管回水压力1
        Unit : bar 
      - Name : 冷冻回水环管温度1
        Unit : "℃"
      - Name : 冷冻回水环管压力1
        Unit : bar
      - Name : 夏季冷却供水环管温度2
        Unit : "℃"
      - Name : 夏季冷却回水环管温度2
        Unit : "℃"
      - Name : 夏季冷却供水环管压力2
        Unit : bar
      - Name : 夏季冷却回水环管压力2
        Unit : bar 
      - Name : 冬季冷却供水环管温度2
        Unit : "℃"
      - Name : 冬季冷却回水环管温度2
        Unit : "℃"
      - Name : 冬季冷却供水环管压力2
        Unit : bar
      - Name : 冬季冷却回水环管压力2
        Unit : bar 
  - Cmd : 3
    Offset : 910
    Len : 58
    Data : 
      - Block : SensorStatus
        index : 末端冷冻环管供水温度2状态
      - Block : SensorStatus
        index : 末端冷冻环管回水温度2状态
      - Block : SensorStatus
        index : 末端冷冻环管供水压力2状态
      - Block : SensorStatus
        index : 末端冷冻环管回水压力2状态
      - Block : SensorStatus
        index : 冷冻回水环管温度2状态
      - Block : SensorStatus
        index : 冷冻回水环管压力2状态
      - Block : SensorStatus
        index : 夏季冷却供水环管温度1状态
      - Block : SensorStatus
        index : 夏季冷却回水环管温度1状态
      - Block : SensorStatus
        index : 夏季冷却供水环管压力1状态
      - Block : SensorStatus
        index : 夏季冷却回水环管压力1状态
      - Block : SensorStatus
        index : 冬季冷却供水环管温度1状态
      - Block : SensorStatus
        index : 冬季冷却回水环管温度1状态
      - Block : SensorStatus
        index : 冬季冷却供水环管压力1状态
      - Block : SensorStatus
        index : 冬季冷却回水环管压力1状态
      - Block : SensorStatus
        index : 电导率状态
      - Block : SensorStatus
        index : 末端冷冻环管供水温度1状态
      - Block : SensorStatus
        index : 末端冷冻环管回水温度1状态
      - Block : SensorStatus
        index : 末端冷冻环管供水压力1状态
      - Block : SensorStatus
        index : 末端冷冻环管回水压力1状态
      - Block : SensorStatus
        index : 冷冻回水环管温度1状态
      - Block : SensorStatus
        index : 冷冻回水环管压力1状态
      - Block : SensorStatus
        index : 夏季冷却供水环管温度2状态
      - Block : SensorStatus
        index : 夏季冷却回水环管温度2状态
      - Block : SensorStatus
        index : 夏季冷却供水环管压力2状态
      - Block : SensorStatus
        index : 夏季冷却回水环管压力2状态
      - Block : SensorStatus
        index : 冬季冷却供水环管温度2状态
      - Block : SensorStatus
        index : 冬季冷却回水环管温度2状态
      - Block : SensorStatus
        index : 冬季冷却供水环管压力2状态
      - Block : SensorStatus
        index : 冬季冷却回水环管压力2状态
