Project:
  Name : XJBAHuanJing
  RT_ID : 5156
  File : "新疆二枢纽BA数据MODBUS_TCP协议25.7.8.xls - 环境"
  DevType : 4
  ProtocolName : 新疆二枢纽BA环境
  Category : 专用空调
BlockTemplate: 
  SensorStatus:
    BlockLength : 4
    BlockType : 'S'
    BlockContent :
      - Name : "%s-断线报警使能"
        CValue : (pData[1] & 0x1)
        Value : ($v[2] & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-预警使能"
        CValue : ((pData[1]>>1) & 0x1)
        Value : (($v[2]>>1) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-报警使能"
        CValue : ((pData[1]>>2) & 0x1)
        Value : (($v[2]>>2) & 0x1)
        Options : 
          - Key : 0
            Value : 未使能
          - Key : 1
            Value : 使能
      - Name : "%s-高报警"
        CValue : ((pData[1]>>3) & 0x1)
        Value : (($v[2]>>3) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-高预警"
        CValue : ((pData[1]>>4) & 0x1)
        Value : (($v[2]>>4) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-低预警"
        CValue : ((pData[1]>>5) & 0x1)
        Value : (($v[2]>>5) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-低报警"
        CValue : ((pData[1]>>6) & 0x1)
        Value : (($v[2]>>6) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
      - Name : "%s-断线报警"
        CValue : ((pData[1]>>9) & 0x1)
        Value : (($v[2]>>9) & 0x1)
        AlertNormalValue : 0
        TeleSignalId : 12083017
Sample : 
  - Cmd : 3
    Offset : 838
    Len : 8
    RType : 'f'
    Data : 
      - Name : 室外温度1
        Unit : ”℃“
      - Name : 室外湿度1
        Unit : ”%“
      - Name : 室外温度2
        Unit : ”℃“
      - Name : 室外湿度2
        Unit : ”%“
  - Cmd : 3
    Offset : 906
    Len : 8
    Data : 
      - Block : SensorStatus
        index : 室外温度1状态
      - Block : SensorStatus
        index : 室外湿度1状态
      - Block : SensorStatus
        index : 室外温度2状态
      - Block : SensorStatus
        index : 室外湿度2状态


