Project:
  Name : XJDXBA513
  RT_ID : 5156
  File : "Device_513.xml 1**.94.82.13:47808"
Sample : 
  - Cmd : 3
    #Offset : [798,799,808,809]
    Offset : [10014,10015,10024,10025]
    Data : [冬季6号板换冷冻侧进水蝶阀手自动状态,冬季7号板换冷冻侧进水蝶阀手自动状态,冬季6号板换冷却侧进水蝶阀手自动状态,冬季7号板换冷却侧进水蝶阀手自动状态]
  - Cmd : 5
    #Offset : [54,55,64,65]
    Offset : [3000374,3000375,3000384,3000385]
    Data : [冬季6号板换冷冻侧进水蝶阀手自动状态1,冬季7号板换冷冻侧进水蝶阀手自动状态1,冬季6号板换冷却侧进水蝶阀手自动状态1,冬季7号板换冷却侧进水蝶阀手自动状态1]
  - Cmd : 0
    #Offset : [790,791,792,793,794,795,796,797,800,801,802,803,804,805,806,807,810,811,812,813,988,991]
    Offset : [10006,10007,10008,10009,10010,10011,10012,10013,10016,10017,10018,10019,10020,10021,10022,10023,10026,10027,10028,10029,11228,11231]
    Data : [冬季6号板换冷冻水进水温度,冬季7号板换冷冻水进水温度,冬季6号板换冷冻水出水温度,冬季7号板换冷冻水出水温度,冬季6号板换冷冻水出水压力,冬季7号板换冷冻水出水压力,冬季6号板换冷冻水进水流量,冬季7号板换冷冻水进水流量,冬季6号板换冷却水进水温度,冬季7号板换冷却水进水温度,冬季6号板换冷却水出水温度,冬季7号板换冷却水出水温度,冬季6号板换冷却水出水压力,冬季7号板换冷却水出水压力,冬季6号板换冷却水进水流量,冬季7号板换冷却水进水流量,冬季6号板换冷冻侧进水蝶阀开度反馈,冬季7号板换冷冻侧进水蝶阀开度反馈,冬季6号板换冷却侧进水蝶阀开度反馈,冬季7号板换冷却侧进水蝶阀开度反馈,软化水箱液位-1,软化水箱液位2]
  - Cmd : 2
    #Offset : [24,25,46,47,48,49,50,51,52,53,56,57,58,59,60,61,62,63,66,67,68,69,70,71,82,83,84,85]
    Offset : [3000344,3000345,3000346,3000347,3000348,3000349,3000350,3000351,3000352,3000366,3000367,3000368,3000369,3000370,3000371,3000372,3000373,3000376,3000377,3000378,3000379,3000380,3000381,3000382,3000383,3000386,3000387,3000388,3000389,3000390,3000391,3000392,3000393,3000394,3000395,3000396,3000397,3000402,3000403,3000404,3000405]
    Data : [调节阀失调报警偏差,调节阀失调报警延时设定,冬季6号板换冷冻水进水温度1,冬季7号板换冷冻水进水温度1,冬季6号板换冷冻水出水温度1,冬季7号板换冷冻水出水温度1,冬季6号板换冷冻水出水压力1,冬季7号板换冷冻水出水压力1,冬季6号板换冷冻水进水流量1,冬季7号板换冷冻水进水流量1,冬季6号板换冷却水进水温度1,冬季7号板换冷却水进水温度1,冬季6号板换冷却水出水温度1,冬季7号板换冷却水出水温度1,冬季6号板换冷却水出水压力1,冬季7号板换冷却水出水压力1,冬季6号板换冷却水进水流量1,冬季7号板换冷却水进水流量1,冬季6号板换冷冻侧进水蝶阀开度反馈1,冬季7号板换冷冻侧进水蝶阀开度反馈1,冬季6号板换冷却侧进水蝶阀开度反馈1,冬季7号板换冷却侧进水蝶阀开度反馈1,软化水箱液位-1a,软化水箱液位2a,冬季6号板换冷冻侧进水蝶阀调节控制,冬季7号板换冷冻侧进水蝶阀调节控制,冬季6号板换冷却侧进水蝶阀调节控制,冬季7号板换冷却侧进水蝶阀调节控制]
  - Cmd : 19
    #Offset : [35,36,37,38,39,40,41,42,43,44,78,79,80,81]
    Offset : [3000355,3000356,3000357,3000358,3000359,3000360,3000361,3000362,3000363,3000364,3000365,3000398,3000399,3000400,3000401]
    Data : [失调报警复位,冬季6号板换锁定命令,冬季7号板换锁定命令,系统启停,冬季8号板换锁定命令,冬季9号板换锁定命令,冬季10号板换锁定命令,冬季8号板换可用,冬季9号板换可用,冬季10号板换可用,冬季6号板换冷冻侧进水蝶阀失调报警,冬季7号板换冷冻侧进水蝶阀失调报警,冬季6号板换冷却侧进水蝶阀失调报警,冬季7号板换冷却侧进水蝶阀失调报警]