Project:
  Name : XJDXBA518
  RT_ID : 5156
  File : "Device_518.xml 1**.94.82.18:47808"
Sample : 
  - Cmd : 3
    Offset : [10009,10010,10011,10012,10013,10014,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024]
    Data : [冷冻水正常工况蓄冷罐旁通阀门（A路）手自动状态,冷冻水正常工况蓄冷罐旁通阀门（A路）开状态,冷冻水正常工况蓄冷罐旁通阀门（A路）关状态,冷冻水正常工况蓄冷罐旁通阀门（B路）手自动状态,冷冻水正常工况蓄冷罐旁通阀门（B路）开状态,冷冻水正常工况蓄冷罐旁通阀门（B路）关状态,蓄冷罐充冷调节阀门（A路）手自动状态,蓄冷罐充冷调节阀门（B路）手自动状态,冷冻水极端工况混水调节阀门（A路）手自动状态,冷冻水极端工况混水调节阀门（B路）手自动状态,冷冻水放冷工况蓄冷罐放冷阀门（A路）手自动状态,冷冻水放冷工况蓄冷罐放冷阀门（A路）开状态,冷冻水放冷工况蓄冷罐放冷阀门（A路）关状态,冷冻水放冷工况蓄冷罐放冷阀门（B路）手自动状态,冷冻水放冷工况蓄冷罐放冷阀门（B路）开状态,冷冻水放冷工况蓄冷罐放冷阀门（B路）关状态]
  - Cmd : 4
    Offset : [10025,10026,10027,10028,10033,10034,10035,10036]
    Data : [冷冻水正常工况蓄冷罐旁通阀门（A路）开控制,冷冻水正常工况蓄冷罐旁通阀门（A路）关控制,冷冻水正常工况蓄冷罐旁通阀门（B路）开控制,冷冻水正常工况蓄冷罐旁通阀门（B路）关控制,冷冻水放冷工况蓄冷罐放冷阀门（A路）开控制,冷冻水放冷工况蓄冷罐放冷阀门（A路）关控制,冷冻水放冷工况蓄冷罐放冷阀门（B路）开控制,冷冻水放冷工况蓄冷罐放冷阀门（B路）关控制]
  - Cmd : 5
    Offset : [3000458,3000459,3000460,3000461,30004623000463,3000464,3000465,3000466,3000467,3000468,3000469,3000470,3000471,3000472,3000473,3000481,3000482,3000483,3000484,3000489,3000490,3000491,3000492]
    Data : [冷冻水正常工况蓄冷罐旁通阀门（A路）手自动状态1,冷冻水正常工况蓄冷罐旁通阀门（A路）开状态1,冷冻水正常工况蓄冷罐旁通阀门（A路）关状态1,冷冻水正常工况蓄冷罐旁通阀门（B路）手自动状态1,冷冻水正常工况蓄冷罐旁通阀门（B路）开状态1,冷冻水正常工况蓄冷罐旁通阀门（B路）关状态1,蓄冷罐充冷调节阀门（A路）手自动状态1,蓄冷罐充冷调节阀门（B路）手自动状态1,冷冻水极端工况混水调节阀门（A路）手自动状态1,冷冻水极端工况混水调节阀门（B路）手自动状态1,冷冻水放冷工况蓄冷罐放冷阀门（A路）手自动状态1,冷冻水放冷工况蓄冷罐放冷阀门（A路）开状态1,冷冻水放冷工况蓄冷罐放冷阀门（A路）关状态1,冷冻水放冷工况蓄冷罐放冷阀门（B路）手自动状态1,冷冻水放冷工况蓄冷罐放冷阀门（B路）开状态1,冷冻水放冷工况蓄冷罐放冷阀门（B路）关状态1,冷冻水正常工况蓄冷罐旁通阀门（A路）开控制1,冷冻水正常工况蓄冷罐旁通阀门（A路）关控制1,冷冻水正常工况蓄冷罐旁通阀门（B路）开控制1,冷冻水正常工况蓄冷罐旁通阀门（B路）关控制1,冷冻水放冷工况蓄冷罐放冷阀门（A路）开控制1,冷冻水放冷工况蓄冷罐放冷阀门（A路）关控制1,冷冻水放冷工况蓄冷罐放冷阀门（B路）开控制1,冷冻水放冷工况蓄冷罐放冷阀门（B路）关控制1]
  - Cmd : 0
    Offset : [10005,10006,10007,10008]
    Data : [蓄冷罐充冷调节阀门（A路）开度反馈,蓄冷罐充冷调节阀门（B路）开度反馈,冷冻水极端工况混水调节阀门（A路）开度反馈,冷冻水极端工况混水调节阀门（B路）开度反馈]
  - Cmd : 1
    Offset : [10029,10030,10031,10032]
    Data : [蓄冷罐充冷调节阀门（A路）开度控制,蓄冷罐充冷调节阀门（B路）开度控制,冷冻水极端工况混水调节阀门（A路）开度控制,冷冻水极端工况混水调节阀门（B路）开度控制]
  - Cmd : 2
    Offset : [3000407,3000429,3000435,3000448,3000450,3000452,3000454,3000455,3000456,3000457,3000474,3000475,3000476,3000477,3000478,3000479,3000480,3000485,3000486,3000487,3000488]
    Data : [冷冻水出水温度设定值偏差,冷冻水出水温度设定值,微冲阀门开度设定,充冷最低开度,充冷阀最大开度,充冷温度设定值,蓄冷罐充冷调节阀门（A路）开度反馈,蓄冷罐充冷调节阀门（B路）开度反馈,冷冻水极端工况混水调节阀门（A路）开度反馈,冷冻水极端工况混水调节阀门（B路）开度反馈,1号蓄冷罐储冷量百分比,5号蓄冷罐储冷量百分比,6号蓄冷罐储冷量百分比,蓄冷罐总储冷量百分比,4号蓄冷罐储冷量百分比,3号蓄冷罐储冷量百分比,2号蓄冷罐储冷量百分比,蓄冷罐充冷调节阀门（A路）开度控制,蓄冷罐充冷调节阀门（B路）开度控制,冷冻水极端工况混水调节阀门（A路）开度控制,冷冻水极端工况混水调节阀门（B路）开度控制]
  - Cmd : 19
    Offset : [3000449,3000451]
    Data : [充冷模式,蓄冷罐模式]