Project:
  Name : XJDXBA515
  RT_ID : 5156
  File : "Device_515.xml 1**.94.82.15:47808"
Sample : 
  - Cmd : 3
    Offset : [10010,10011,10012,10013,10015,10016,10017,10018]
    Data : [备-1号冷冻泵电源状态,备-1号冷冻泵运行状态,备-1号冷冻泵故障报警,备-1号冷冻泵手自动状态,备-2号冷冻泵电源状态,备-2号冷冻泵运行状态,备-2号冷冻泵故障状态,备-2号冷冻泵手自动状态]
  - Cmd : 4
    Offset : [10019,10020,10021,10022]
    Data : [备-1号冷冻泵启动控制,备-1号冷冻泵停止控制,备-2号冷冻泵启动控制,备-2号冷冻泵停止控制]
  - Cmd : 5
    Offset : [3000084,3000085,3000086,3000087,3000088,3000089,3000090,3000091,3000097,3000098,3000099,3000100]
    Data : [备-1号冷冻泵电源状态1,备-1号冷冻泵运行状态1,备-1号冷冻泵故障报警1,备-1号冷冻泵手自动状态1,备-2号冷冻泵电源状态1,备-2号冷冻泵运行状态1,备-2号冷冻泵故障状态1,备-2号冷冻泵手自动状态1,备-1号冷冻泵启动控制1,备-1号冷冻泵停止控制1备-2号冷冻泵启动控制1,备-2号冷冻泵停止控制1]
  - Cmd : 0
    Offset : [10002,10003,10005,10006,10007]
    Data : [备—1号冷冻泵频率反馈,备—2号冷冻泵频率反馈,一次环路冷冻水供水压力（A路）-分水点前,一次环路冷冻水供水压力（B路）-分水点前,冷冻泵主用控柜至冷冻泵备用柜心跳输入]
  - Cmd : 1
    Offset : [10023,10024,10025]
    Data : [备-1冷冻泵频率调节,备-2号冷冻泵频率调节,冻泵备用控制至冷冻泵主用控柜心跳输出]
  - Cmd : 2
    Offset : [3000062,3000063,3000064,3000065,3000066,3000067,3000068,3000069,3000070,3000071,3000079,3000080,3000081,3000082,3000083,3000092,3000093,3000101,3000102,3000103]
    Data : [冷却泵失调报警延时设定,冷冻水泵最大运行频率设定,冷冻水泵最小运行频率设定,冷冻水泵关延时设定,压差设定值,加减机抑制时间,减机频率设定,减机条件成立延时设定,加机频率设定,加机条件成立延时设定,备—1号冷冻泵频率反馈1,备—2号冷冻泵频率反馈1,一次环路冷冻水供水压力（A路）-分水点前1,一次环路冷冻水供水压力（B路）-分水点前1,冷冻泵主用控柜至冷冻泵备用柜心跳输入1,系统开启数量,最大可用数量,备-1冷冻泵频率调节,备-2号冷冻泵频率调节,冻泵备用控制至冷冻泵主用控柜心跳输出]
  - Cmd : 19
    Offset : [3000073,3000074,3000075,3000094,3000095,3000096]
    Data : [主-1号冷冻泵锁定命令,主-2号冷冻泵锁定命令,失调报警复位,主-1号冷冻泵失调报警,主-2号冷冻泵失调报警,备用控制器心跳故障]