Project:
  Name : XJDXBA511
  RT_ID : 5156
  File : "Device_511.xml 1**.94.82.11:47808"
Sample : 
  - Cmd : 3
    Offset : [10013,10014,10016,10017]
    Data : [3号冷机运行状态,3号冷机故障报警,3号冷机冷冻侧进水蝶阀手自动状态,3号冷机冷却侧进水蝶阀手自动状态]
  - Cmd : 4
    Offset : [10018,10019]
    Data : [3号冷机启动控制,3号冷机停止控制]
  - Cmd : 5
    Offset : [3000082,3000083,3000084,3000085,3000090,3000091]
    Data : [3号冷机运行状态1,3号冷机故障报警1,3号冷机冷冻侧进水蝶阀手自动状态1,3号冷机冷却侧进水蝶阀手自动状态1,3号冷机启动控制1,3号冷机停止控制1]
  - Cmd : 0
    Offset : [10002,10003,10005,10006,10007,10008,10009,10010,10011,10012]
    Data : [3号冷机冷冻水进水温度,3号冷机冷冻水出水温度,3号冷机冷冻水出水压力,3号冷机冷冻水进水流量,3号冷机冷却水进水温度,3号冷机冷却水出水温度,3号冷机冷却水出水压力,3号冷机冷却水进水流量,3号冷机冷冻侧进水蝶阀开度反馈,3号冷机冷却侧进水蝶阀开度反馈]
  - Cmd : 1
    Offset : [10020,10021]
    Data : [3号冷机冷冻侧进水蝶阀调节控制,3号冷机冷却侧进水蝶阀调节控制]
  - Cmd : 2
    Offset : [3000056,3000057,3000058,3000059,3000060,3000072,3000073,3000074,3000075,3000076,3000077,3000078,3000079,3000080,3000081,3000092,3000093]
    Data : [调节阀失调报警偏差,调节阀失调报警延时设定,冷冻水蝶阀关闭延时,冷却水蝶阀关闭延时,冷机失调报警延时设定,3号冷机冷冻水进水温度1,3号冷机冷冻水出水温度1,3号冷机冷冻水出水压力1,3号冷机冷冻水进水流量1,3号冷机冷却水进水温度1,3号冷机冷却水出水温度1,3号冷机冷却水出水压力1,3号冷机冷却水进水流量,3号冷机冷冻侧进水蝶阀开度反馈1,3号冷机冷却侧进水蝶阀开度反馈1,3号冷机冷冻侧进水蝶阀调节控制,3号冷机冷却侧进水蝶阀调节控制]
  - Cmd : 19
    Offset : [3000062,3000063,3000064,3000065,3000068,3000069,3000086,3000087,3000088]
    Data : [冷机失调报警命令,冷机软件手自动点,冷机软件故障点,冷机软件状态点,失调报警复位,系统锁定命令,3号冷机失调报警,3号冷机冷冻侧进水蝶阀失调报警,3号冷机冷却侧进水蝶阀失调报警]