Project:
  Name : XJDXBA512
  RT_ID : 5156
  File : "Device_512.xml 1**.94.82.12:47808"
Sample : 
  - Cmd : 3
    Offset : [10014,10015,10024,10025]
    Data : [夏季1号板换冷冻侧进水蝶阀手自动状态,夏季2号板换冷冻侧进水蝶阀手自动状态,夏季1号板换冷却侧进水蝶阀手自动状态,夏季2号板换冷却侧进水蝶阀手自动状态]
  - Cmd : 5
    Offset : [3000274,3000275,3000295,3000296,3000305,3000306]
    Data : [冷冻泵运行状态,夏季冷却泵运行状态,夏季1号板换冷冻侧进水蝶阀手自动状态1,夏季2号板换冷冻侧进水蝶阀手自动状态1,夏季1号板换冷却侧进水蝶阀手自动状态1,夏季2号板换冷却侧进水蝶阀手自动状态1]
  - Cmd : 0
    Offset : [10006,10007,10008,10009,10010,10011,10012,10013,10016,10017,10018,10019,10020,10021,10022,10023,10026,10027,10028,10029,11228,11231]
    Data : [夏季1号板换冷冻水进水温度,夏季2号板换冷冻水进水温度,夏季1号板换冷冻水出水温度,夏季2号板换冷冻水出水温度,夏季1号板换冷冻水出水压力,夏季2号板换冷冻水出水压力,夏季1号板换冷冻水进水流量,夏季2号板换冷冻水进水流量,夏季1号板换冷却水进水温度,夏季2号板换冷却水进水温度,夏季1号板换冷却水出水温度,夏季2号板换冷却水出水温度,夏季1号板换冷却水出水压力,夏季2号板换冷却水出水压力,夏季1号板换冷却水进水流量,夏季2号板换冷却水进水流量,夏季1号板换冷冻侧进水蝶阀开度反馈,夏季2号板换冷冻侧进水蝶阀开度反馈,夏季1号板换冷却侧进水蝶阀开度反馈,夏季2号板换冷却侧进水蝶阀开度反馈,乙二醇水箱液位1,乙二醇水箱液位2]
  - Cmd : 2
    Offset : [3000265,3000266,3000268,3000269,3000270,3000271,3000272,3000273,3000287,3000288,3000289,3000290,3000291,3000292,3000293,3000294,3000297,3000298,3000299,3000300,3000301,3000302,3000303,3000304,3000307,3000308,3000309,3000310,3000311,3000312,3000313,3000314,3000315,3000316,3000317,3000318,3000323,3000324,3000325,3000326]
    Data : [调节阀失调报警偏差,调节阀失调报警延时设定,夏季1号板换运行时间,夏季2号板换运行时间,夏季2号板换运行时间,夏季4号板换运行时间,夏季5号板换运行时间,阀门关延时设定,夏季1号板换冷冻水进水温度,夏季2号板换冷冻水进水温度,夏季1号板换冷冻水出水温度,夏季2号板换冷冻水出水温度,夏季1号板换冷冻水出水压力,夏季2号板换冷冻水出水压力,夏季1号板换冷冻水进水流量,夏季2号板换冷冻水进水流量,夏季1号板换冷却水进水温度,夏季2号板换冷却水进水温度,夏季1号板换冷却水出水温度,夏季2号板换冷却水出水温度,夏季1号板换冷却水出水压力,夏季2号板换冷却水出水压力,夏季1号板换冷却水进水流量,夏季2号板换冷却水进水流量,夏季1号板换冷冻侧进水蝶阀开度反馈,夏季2号板换冷冻侧进水蝶阀开度反馈,夏季1号板换冷却侧进水蝶阀开度反馈,夏季2号板换冷却侧进水蝶阀开度反馈,乙二醇水箱液位1,乙二醇水箱液位2,夏季3号板换冷冻侧进水蝶阀调节控制输出,夏季3号板换冷却侧进水蝶阀调节控制输出,夏季5号板换冷冻侧进水蝶阀调节控制输出,夏季5号板换冷却侧进水蝶阀调节控制输出,夏季4号板换冷冻侧进水蝶阀调节控制输出,夏季4号板换冷却侧进水蝶阀调节控制输出,夏季1号板换冷冻侧进水蝶阀调节控制,夏季2号板换冷冻侧进水蝶阀调节控制,夏季1号板换冷却侧进水蝶阀调节控制,夏季2号板换冷却侧进水蝶阀调节控制]
  - Cmd : 19
    Offset : [3000276,3000277,3000278,3000279,3000280,3000281,3000282,3000283,3000284,3000285,3000286,3000319,3000320,3000321,3000322]
    Data : [失调报警复位,夏季1号板换锁定命令,夏季2号板换锁定命令,系统启停,夏季3号板换锁定命令,夏季4号板换锁定命令,夏季5号板换锁定命令,夏季3号板换可用,夏季4号板换可用,夏季5号板换可用,夏季模式,夏季1号板换冷冻侧进水蝶阀失调报警,夏季2号板换冷冻侧进水蝶阀失调报警,夏季1号板换冷却侧进水蝶阀失调报警,夏季2号板换冷却侧进水蝶阀失调报警]