Project:
  Name : XJDXBA516
  RT_ID : 5156
  File : "Device_516.xml 1**.94.82.16:47808"
Sample : 
  - Cmd : 3
    Offset : [10007,10008,10009,10010,10011,10012,10013,10015,10016,10017,10018,10026,10027,10028,10029,10030]
    Data : [冬季1号冷却泵电源状态,冬季1号冷却泵运行状态,冬季1号冷却泵故障报警,冬季2号冷却泵电源状态,冬季2号冷却泵运行状态,冬季2号冷却泵故障报警,冬季2号冷却泵手自动状态,夏季1号冷却泵电源状态,夏季1号冷却泵运行状态,夏季1号冷却泵故障报警,夏季1号冷却泵手自动状态,冬季1号冷却泵手自动状态,夏季2号冷却泵电源状态,夏季2号冷却泵运行状态,夏季2号冷却泵故障报警,夏季2号冷却泵手自动状态]
  - Cmd : 5
    Offset : [3000652,3000653,3000654,3000655,3000656,3000657,3000658,3000659,3000660,3000661,3000662,3000663,3000664,3000665,3000666,3000667,3000690,3000691,3000692,3000693,3000698,3000699,3000700,3000701]
    Data : [冬季1号冷却泵电源状态1,冬季1号冷却泵运行状态1,冬季1号冷却泵故障报警1,冬季2号冷却泵电源状态1,冬季2号冷却泵运行状态1,冬季2号冷却泵故障报警1,冬季2号冷却泵手自动状态1,夏季1号冷却泵电源状态1,夏季1号冷却泵运行状态1,夏季1号冷却泵故障报警1,夏季1号冷却泵手自动状态1,冬季1号冷却泵手自动状态1,夏季2号冷却泵电源状态1,夏季2号冷却泵运行状态1,夏季2号冷却泵故障报警1,夏季2号冷却泵手自动状态1,冬季1号冷却泵启动控制,冬季1号冷却泵停止控制,冬季2号冷却泵启动控制,冬季2号冷却泵停止控制,夏季1号冷却泵启动控制,夏季1号冷却泵停止控制,夏季2号冷却泵启动控制,夏季2号冷却泵停止控制]
  - Cmd : 0
    Offset : [10002,10003,10005,10006]
    Data : [冬季1号冷却泵频率反馈,冬季2号冷却泵频率反馈,夏季1号冷却泵频率反馈,夏季2号冷却泵频率反馈]
  - Cmd : 1
    Offset : [10023,10024,10025,10031]
    Data : [冬季1号冷却泵频率调节,冬季2号冷却泵频率调节,夏季1号冷却泵频率调节,夏季2号冷却泵频率调节]
  - Cmd : 2
    Offset : [3000603,3000604,3000605,3000606,3000607,3000608,3000609,3000610,3000611,3000612,3000613,3000614,3000615,3000616,3000617,3000618,3000619,3000620,3000621,3000622,3000623,3000624,3000625,3000648,3000649,3000650,3000651,3000668,3000669,3000670,3000671,3000672,3000673,3000694,3000695,3000696,3000697]
    Data : [冷却泵失调报警延时设定,冷却水泵最大运行频率设定,冷却水泵最小运行频率设定,冬季冷却水泵关延时设定,冷冻水泵最大运行频率设定,冷冻水泵最小运行频率设定,夏季冷却水泵关延时设定,夏季1号冷却泵运行时间,夏季2号冷却泵运行时间,夏季3号冷却泵运行时间,夏季4号冷却泵运行时间,夏季5号冷却泵运行时间,冬季1号冷却泵运行时间,冬季2号冷却泵运行时间,冬季3号冷却泵运行时间,冬季4号冷却泵运行时间,冬季5号冷却泵运行时间,冬季工况冷却水总管温差输入,冬季冷却水温差设定值,夏季冷却水温差设定值,冬季1号冷却泵频率反馈1,冬季2号冷却泵频率反馈1,夏季1号冷却泵频率反馈1,夏季2号冷却泵频率反馈1,夏季4号冷却泵频率输出,夏季5号冷却泵频率输出,冬季5号冷却泵频率输出,夏季3号冷却泵频率输出,冬季3号冷却泵频率输出,冬季4号冷却泵频率输出,冬季1号冷却泵频率调节,冬季2号冷却泵频率调节,夏季1号冷却泵频率调节,夏季2号冷却泵频率调节]
  - Cmd : 19
    Offset : [3000597,3000598,3000599,3000600,3000601,3000602,3000626,3000633,3000634,3000635,3000636,3000637,3000638,3000639,3000640,3000641,3000642,3000643,3000644,3000645,3000646,3000647,3000674,3000675,3000676,3000677,3000678,3000679,3000680,3000681,3000682,3000683,3000684,3000685,3000686,3000687,3000688,3000689]
    Data : [夏季3号冷却泵运行状态输入,夏季4号冷却泵运行状态输入,冬季5号冷却泵运行状态输入,冬季4号冷却泵运行状态输入,冬季3号冷却泵运行状态输入,夏季5号冷却泵运行状态输入,失调报警复位,夏季1号冷却泵锁定命令,夏季2号冷却泵锁定命令,夏季3号冷却泵锁定命令,夏季4号冷却泵锁定命令,夏季5号冷却泵锁定命令,东季1号冷却泵锁定命令,东季2号冷却泵锁定命令,冬季3号冷却泵锁定命令,冬季4号冷却泵锁定命令,冬季5号冷却泵锁定命令,夏季阀门状态,冬季阀门状态,系统启停,冬季模式,夏季模式,冬季1号冷却泵失调报警,冬季2号冷却泵失调报警,夏季1号冷却泵失调报警,夏季2号冷却泵失调报警,夏季3号冷却泵开启控制输出,夏季4号冷却泵开启控制输出,夏季5号冷却泵关闭控制输出,冬季5号冷却泵开启控制输出,冬季4号冷却泵开启控制输出,冬季3号冷却泵关闭控制输出,夏季4号冷却泵关闭控制输出,冬季3号冷却泵开启控制输出,夏季5号冷却泵开启控制输出,夏季3号冷却泵关闭控制输出,冬季5号冷却泵关闭控制输出,冬季4号冷却泵关闭控制输出]