Project:
  Name : XJDXBA500
  RT_ID : 5156
  File : "Device_500.xml 1**.94.82.10:47808"
  DevType : 4
  ProtocolName : BacNET-Device_500
  Category : 专用空调
Sample : 
  - Cmd : 3
    #Offset : [798,799,808,809]
    Offset : [10014,10015,10024,10025]
    Data : [冬季8号板换冷冻侧进水蝶阀手自动状态, 冬季9号板换冷冻侧进水蝶阀手自动状态, 冬季8号板换冷却侧进水蝶阀手自动状态, 冬季9号板换冷却侧进水蝶阀手自动状态 ]
  - Cmd : 5
    #Offset : [756,757,766,767]
    Offset : [3000052,3000053,3000062,3000063]
    Data : [冬季8号板换冷冻侧进水蝶阀手自动状态1, 冬季9号板换冷冻侧进水蝶阀手自动状态1, 冬季8号板换冷却侧进水蝶阀手自动状态1, 冬季9号板换冷却侧进水蝶阀手自动状态1 ]
  - Cmd : 0
    #Offset : [790,791,792,793,794,795,796,797,800,801,802,803,804,805,806,807,810,812]
    Offset : [10006,10007,10008,10009,10010,10011,10012,10013,10016,10017,10018,10019,10020,10021,10022,10023,10026,10028]
    Data : [冬季8号板换冷冻水进水温度,冬季9号板换冷冻水进水温度,冬季8号板换冷冻水出水温度,冬季9号板换冷冻水出水温度,冬季8号板换冷冻水出水压力,冬季9号板换冷冻水出水压力,冬季8号板换冷冻水进水流量,冬季9号板换冷冻水进水流量,冬季8号板换冷却水进水温度,冬季9号板换冷却水进水温度,冬季8号板换冷却水出水温度,冬季9号板换冷却水出水温度,冬季8号板换冷却水出水压力,冬季9号板换冷却水出水压力,冬季8号板换冷却水进水流量,冬季9号板换冷却水进水流量,冬季8号板换冷冻侧进水蝶阀开度反馈,冬季8号板换冷却侧进水蝶阀开度反馈]
  - Cmd : 1
    #Offset : [814, 815, 816, 817]
    Offset : [10030,10031,10032,10033]
    Data : [冬季8号板换冷冻侧进水蝶阀调节控制1, 冬季9号板换冷冻侧进水蝶阀调节控制1, 冬季8号板换冷却侧进水蝶阀调节控制1, 冬季9号板换冷却侧进水蝶阀调节控制1]
  - Cmd : 2
    #Offset : [738,739,740,741,742,743,744,745,748,749,750,751,752,753,754,755,758,759,760,761,762,763,764,765,768,769,776,777,778,779]
    Offset : [3000034,3000035,3000036,3000037,3000038,3000039,3000040,3000041,3000044,3000045,3000046,3000047,3000048,3000049,3000050,3000051,3000054,3000055,3000056,3000057,3000058,3000059,3000060,3000061,3000064,3000065,3000072,3000073,3000074,3000075]
    Data : [冬季9号板换冷冻侧进水蝶阀调节控制输入,冬季9号板换冷却侧进水蝶阀调节控制输入,冬季8号板换冷冻侧进水蝶阀调节控制输入,冬季8号板换冷却侧进水蝶阀调节控制输入,冬季9号板换冷冻侧进水蝶阀开度反馈,冬季9号板换冷却侧进水蝶阀开度反馈,调节阀失调报警偏差,调节阀失调报警延时设定,冬季8号板换冷冻水进水温度,冬季9号板换冷冻水进水温度,冬季8号板换冷冻水出水温度,冬季9号板换冷冻水出水温度,冬季8号板换冷冻水出水压力,冬季9号板换冷冻水出水压力,冬季8号板换冷冻水进水流量,冬季9号板换冷冻水进水流量,冬季8号板换冷却水进水温度,冬季9号板换冷却水进水温度,冬季8号板换冷却水出水温度,冬季9号板换冷却水出水温度,冬季8号板换冷却水出水压力,冬季9号板换冷却水出水压力,冬季8号板换冷却水进水流量,冬季9号板换冷却水进水流量,冬季8号板换冷冻侧进水蝶阀开度反馈,冬季8号板换冷却侧进水蝶阀开度反馈,冬季8号板换冷冻侧进水蝶阀调节控制,冬季9号板换冷冻侧进水蝶阀调节控制,冬季8号板换冷却侧进水蝶阀调节控制,冬季9号板换冷却侧进水蝶阀调节控制]
  - Cmd : 19
    #Offset : [746,747,770,771,772,773,774,775]
    Offset : [3000042,3000043,3000066,3000067,3000068,3000069,3000070,3000071]
    Data : [失调报警复位,系统启停,冬季8号板换可用状态,冬季9号板换可用状态,冬季8号板换冷冻侧进水蝶阀失调报警,冬季9号板换冷冻侧进水蝶阀失调报警,冬季8号板换冷却侧进水蝶阀失调报警,冬季9号板换冷却侧进水蝶阀失调报警]